AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Events Microservice

Globals:
  Function:
    Timeout: 20

Resources:
  EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: io.devwidgets.events.api.lambda.LambdaHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      FunctionName: event-ms
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - Statement:
            - Sid: DynamoDBReadPolicy
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EventsDynamoDbTable}
      Tags:
        channel: DevWidgets
        series: serverless-101
        episode: 004

  EventsDynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Events
      Tags:
        channel: DevWidgets
        series: serverless-101
        episode: 004

Outputs:
  EventsFunction:
    Description: Event Functions Arn
    Value: !GetAtt EventsFunction.Arn
  EventFunctionRole:
    Description: Implicit IAM Role created for EventsFunction
    Value: !GetAtt EventsFunctionRole.Arn
  EventApiGatewayProdState:
    Description: Implicit Prod Stage url for API Gateway
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

